# Generated by Django 4.2.24 on 2025-09-18 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionDetail', models.TextField()),
                ('contactList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contactlist')),
            ],
        ),
    ]
