# Generated by Django 4.2.24 on 2025-09-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='specfile',
            field=models.FileField(blank=True, null=True, upload_to='specfile'),
        ),
    ]
